### ISSUE TITLE
sandi_meter-1.0.3 doesn't work with Ruby 1.9

### ISSUE THREAD

**Issue by bkpavan** [makaroni4/sandi_meter#30]
Issue:
sandi_meter-1.0.3 doesn't work with Ruby 1.9

Cause:
sandi_meter-1.0.3/lib/sandi_meter/formatter.rb:81: undefined method `prepend'
sandi_meter-1.0.3/lib/sandi_meter/html_generator.rb:133: undefined method`prepend'

Solution:
Fix the prepend call with an alternate implementation
